# Generated by Django 5.2.12 on 2026-03-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramCredential',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('token_encrypted', models.TextField()),
                ('chat_id_hash', models.CharField(max_length=64, unique=True)),
                ('bot_username', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='telegram_config',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Credencial Telegram',
                'verbose_name_plural': 'Credenciais Telegram',
            },
        ),
    ]
