# Generated by Django 5.2.12 on 2026-03-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramcredential',
            name='chat_id_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
