# Generated by Django 5.2.12 on 2026-03-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-data', '-id'], 'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
    ]
