# Generated by Django 5.2.12 on 2026-03-28 12:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_transaction_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('event_type', models.CharField(choices=[('threshold_20', 'Faltam 20%'), ('threshold_10', 'Faltam 10%'), ('limit_reached', 'Limite atingido'), ('post_limit_expense', 'Despesa após limite')], max_length=32)),
                ('mensagem', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_alerta_orcamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Alerta de Orçamento',
                'verbose_name_plural': 'Eventos de Alerta de Orçamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda_mensal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('limite_percentual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('alertas_ativos', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_mensal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Orçamento Mensal',
                'verbose_name_plural': 'Configurações de Orçamento Mensal',
            },
        ),
    ]
